# Skip commits on updating git specific stuff. No actual project changes in this case so pointless to build.
skip_commits:
 files:
   - .gitignore
   - README.md

init:
  - ps: '$env:WK_BUILD_TIME = "[UTC+2]: " + $(Get-Date).ToLongDateString() + " " + $((Get-Date).ToUniversalTime().AddHours(+2).ToLongTimeString())'
  - ps: $env:WK_VERSION = "$(Get-Date -format yyyy.MM.dd)-$env:APPVEYOR_REPO_COMMIT"
  - ps: Update-AppveyorBuild -Version $env:WK_VERSION

clone_script:
- cmd: git clone -q --depth=99999 --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

# Update to the most recent VS.
image: Visual Studio 2017

test: off

build:
  parallel: true   
  project: WolvenKit.sln
  verbosity: minimal

platform: Any CPU
configuration: Release

before_build:
  - nuget restore
after_build:
  - cd %APPVEYOR_BUILD_FOLDER%\WolvenKit\bin\Release\
  - rm *.xml
  - rm *.config
  - rm *.pdb
  - cd /
  - 7z a WolvenKit.zip %APPVEYOR_BUILD_FOLDER%\WolvenKit\bin\Release\*
  - appveyor PushArtifact WolvenKit.zip

deploy:
  release: WolvenKit-v$(appveyor_build_version)
  tag: Latest
  description: This is a beta release so you may encounter bugs. Please report them. This build was generated on $(WK_BUILD_TIME)
  provider: GitHub
  auth_token:
    secure: PVcjhc6iNEsA28A1clj8BTACho8kddrMQXuFtLoTnJo9wgaQ8erwBvwGd+tMFQT6
  artifact: WolvenKit.zip
  prerelease: true
  force_update: true
