name: WolvenKit-Check-Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2
    - name: Setup 7z, wget with choco
      run: |
        choco install 7zip.install -y
        choco install wget -y
    - name: Download libs for irrlicht
      run: |
        cd $Env:GITHUB_WORKSPACE\\WolvenKit.Irrlicht\\
        wget https://outwa.it/lib.zip
        7zip  -y x lib.zip
    - name: Setup Nuget.exe
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: latest
    - name: Restore packages
      run: nuget restore WolvenKit.sln
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
    - name: Build with MSBuild
      run: msbuild  WolvenKit.sln -p:Configuration=Release -p:Platform=x64 -m
