name: WolvenKit-Nightly
on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  wkit-win:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: dotnet clean
      run: dotnet clean ./WolvenKit.sln --configuration Release && dotnet nuget locals all --clear
    - name: dotnet restore
      run: dotnet restore ./WolvenKit.sln 

    - name: dotnet build WolvenKit.sln
      run: dotnet build ./WolvenKit.sln --configuration Release --no-restore

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: artifact_wkit-windows
        path: ./WolvenKit/bin/Release/net5.0-windows

    - name: zip
      uses: papeloto/action-zip@v1
      with:
        files: ./WolvenKit/bin/Release/net5.0-windows
        dest: wolvenkit.zip
    - name: Deploy Nightly
      uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/WolvenKit/Wolven-kit/releases/11743470/assets{?name,label}
        release_id: 11743470
        asset_path: wolvenkit.zip
        asset_name: WolvenKit-Nightly-$$.zip
        asset_content_type: application/zip
